import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <link rel="icon" type="image/svg" sizes="32x32" href="/favicon.svg"></link>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
